changelog:
  - type: NEW_FEATURE
    description: |
      Adds the ability to configure WebSocket upgrades on the HTTP Connection Manager and/or as part of a route's options.
    issueLink: https://github.com/solo-io/gloo-edge/issues/1132
