changelog:
  - type: NEW_FEATURE
    description: Solves part of https://github.com/solo-io/gloo-edge/issues/668 - allow configuration connection settings.
    resolvesIssue: false
    issueLink: https://github.com/solo-io/gloo-edge/issues/668
