name: Update solo-apis
on: pull_request
#on:
#  release:
#    types: [created]'
jobs:
  publish-apis:
    name: Publish Gloo APIs
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: gloo
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: solo-io/solo-apis
          path: solo-apis
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SOLO_API_DEPLOY_KEY }}
      - name: Update solo-apis
        run: |
          cd solo-apis
          touch a.txt
          git add .
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git commit -m "Sync Gloo APIs"
          git checkout -b update-apis
          git remote add solo-apis git@github.com:solo-io/solo-apis.git
          git push solo-apis update-apis