name: Update solo-apis
on: pull_request
#on:
#  release:
#    types: [created]'
jobs:
  publish-apis:
    name: Publish Gloo APIs
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: gloo
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: solo-io/solo-apis
          path: solo-apis
      - name: Update solo-apis
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cd solo-apis
          make mod-download update-deps; ./hack/sync-gloo-apis.sh; make generate -B
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global url."https://${TOKEN}@github.com/solo-io/".insteadOf "https://github.com/solo-io/"
          git checkout -b update-solo-apis
          git add .
          git commit -m "Sync Gloo APIs to ${{ github.event.release.tag_name }}"
          git push --set-upstream origin update-solo-apis