name: Update solo-apis
on: pull_request
#on:
#  release:
#    types: [created]'
jobs:
  publish-apis:
    name: Publish Gloo APIs
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: gloo
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: solo-io/solo-apis
          path: solo-apis
      - name: Update solo-apis
        run: |
          cd solo-apis
          touch a.txt
      - name: Commit files
        run: |
          cd solo-apis
          git add .
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git commit -m "Sync Gloo APIs to"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: solo-io/solo-apis
          directory: solo-apis
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: update-gloo-apis-github-action